version: '3.9'

services:
  redis_db:
    extra_hosts: # for  Linux hosts since version 20.10
      - dockerhost:host-gateway
    extends:
      file: ./services/docker-compose-redis.yml
      service: redis_db

  postgres-db-init:
    extra_hosts: # for  Linux hosts since version 20.10
      - dockerhost:host-gateway
    extends:
      file: ./services/docker-compose-db.yml
      service: postgres-db-init

  postgres-db:
    extra_hosts: # for  Linux hosts since version 20.10
      - dockerhost:host-gateway
    extends:
      file: ./services/docker-compose-db.yml
      service: postgres-db

  backend:
    extra_hosts: # for  Linux hosts since version 20.10
      - dockerhost:host-gateway
    depends_on:
      - postgres-db
      - redis_db
    extends:
      file: ./services/docker-compose-backend.yml
      service: backend
    links:
      - postgres-db:database
    environment:
      ETHEREUM_JSONRPC_VARIANT: 'geth'

  visualizer:
    extra_hosts: # for  Linux hosts since version 20.10
      - dockerhost:host-gateway
    extends:
      file: ./services/docker-compose-visualizer.yml
      service: visualizer

  sig-provider:
    extra_hosts: # for  Linux hosts since version 20.10
      - dockerhost:host-gateway
    extends:
      file: ./services/docker-compose-sig-provider.yml
      service: sig-provider

  frontend:
    extra_hosts: # for  Linux hosts since version 20.10
      - dockerhost:host-gateway
    depends_on:
      - backend
    extends:
      file: ./services/docker-compose-frontend.yml
      service: frontend
    ports:
      - 3008:3000

  stats-db-init:
    extra_hosts: # for  Linux hosts since version 20.10
      - dockerhost:host-gateway
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats-db-init

  stats-db:
    extra_hosts: # for  Linux hosts since version 20.10
      - dockerhost:host-gateway
    depends_on:
      - backend
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats-db

  stats:
    extra_hosts: # for  Linux hosts since version 20.10
      - dockerhost:host-gateway
    depends_on:
      - stats-db
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats

  proxy:
    extra_hosts: # for  Linux hosts since version 20.10
      - dockerhost:host-gateway
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/docker-compose-nginx.yml
      service: proxy
