version: '3.9'

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    extends:
      file: ./services/db.yml
      service: db

  backend:
    extends:
      file: ./services/backend.yml
      service: backend
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        CHAIN_ID: '3007'

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider

  frontend:
    extends:
      file: ./services/frontend.yml
      service: frontend

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  stats-db:
    extends:
      file: ./services/stats.yml
      service: stats-db

  stats:
    extends:
      file: ./services/stats.yml
      service: stats

  proxy:
    extends:
      file: ./services/nginx.yml
      service: proxy
