services:
  #Blockscout begin
  redis-db:
    extends:
      file: ../explorer/blockscout/geth.yml
      service: redis-db
    networks:
      op-local:
        ipv4_address: 192.168.10.33

  db-init:
    extends:
      file: ../explorer/blockscout/geth.yml
      service: db-init

  db:
    extends:
      file: ../explorer/blockscout/geth.yml
      service: db
    networks:
      op-local:
        ipv4_address: 192.168.10.34
        aliases:
          - database
    depends_on:
      db-init:
        condition: service_started

  backend:
    extends:
      file: ../explorer/blockscout/geth.yml
      service: backend
    ports:
      - 4005:4005
    networks:
      op-local:
        ipv4_address: 192.168.10.35
    depends_on:
      db:
        condition: service_started
      redis-db:
        condition: service_started

  frontend:
    extends:
      file: ../explorer/blockscout/geth.yml
      service: frontend
    ports:
      - 3000:3000
    networks:
      op-local:
        ipv4_address: 192.168.10.36
    depends_on:
      - backend

  visualizer:
    extends:
      file: ../explorer/blockscout/geth.yml
      service: visualizer
    networks:
      op-local:
        ipv4_address: 192.168.10.38

  sig-provider:
    extends:
      file: ../explorer/blockscout/geth.yml
      service: sig-provider
    networks:
      op-local:
        ipv4_address: 192.168.10.39

  stats-db-init:
    extends:
      file: ../explorer/blockscout/geth.yml
      service: stats-db-init

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_started
    extends:
      file: ../explorer/blockscout/geth.yml
      service: stats-db
    networks:
      op-local:
        ipv4_address: 192.168.10.41

  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ../explorer/blockscout/geth.yml
      service: stats
    networks:
      op-local:
        ipv4_address: 192.168.10.42

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ../explorer/blockscout/geth.yml
      service: proxy
    ports:
      - 80:80
      - 8087:8080
      - 8085:8085
    networks:
      op-local:
        ipv4_address: 192.168.10.43
  #  blockscout end

networks:
  op-local:
    name: op-local
    external: true
