services:
  prometheus:
    image: ${CW_PROMETHEUS_IMAGE}
    restart: on-failure
    container_name: prometheus
    extra_hosts: # for  Linux hosts since version 20.10
      - dockerhost:host-gateway
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
