{
 "title": "Custom Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "quantille", "query": { "query": "label_values(quantile)" } },
   { "name": "le", "query": { "query": "label_values(le)" } }
  ]
 },
 "panels": [
  {
   "title": "Geth chain(block) data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "chain_inserts{quantile=\"$quantille\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "chain_write{quantile=\"$quantille\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "chain_validation{quantile=\"$quantille\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "chain_execution{quantile=\"$quantille\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpGeth Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 0 },
   "targets": [
    { "expr": "rpc_requests", "legendFormat": "__auto" },
    { "expr": "rpc_failure", "legendFormat": "__auto" },
    { "expr": "rpc_success", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Op-Node sequencer data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "op_node_default_sequencer_building_diff_seconds_bucket{le=\"$le\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "op_node_default_sequencer_sealing_seconds_bucket{le=\"$le\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Op-Node Transaction sequenced total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "op_node_default_transactions_sequenced_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}