services:

  #influx begin
  influxdb:
    # Full tag list: https://hub.docker.com/r/library/influxdb/tags/
    image: influxdb:1.8.10
    container_name: influxdb
    restart: unless-stopped
    extra_hosts: # for  Linux hosts since version 20.10
      - dockerhost:host-gateway
    volumes:
      - ./influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf
      - ../../data/influxdb/data:/var/lib/influxdb
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
      - "8083:8083"

  #  telegraf:
  #    image: telegraf:alpine
  #    container_name: telegraf
  #    restart: unless-stopped
  #    extra_hosts: # for  Linux hosts since version 20.10
  #      - dockerhost:host-gateway
  #    environment:
  #      HOSTNAME: "telegraf-getting-started"
  #    # Telegraf requires network access to InfluxDB
  #    links:
  #      - influxdb
  #    volumes:
  #      # Mount for telegraf configuration
  #      - ./telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf
  #      # Mount for Docker API access
  #      - /var/run/docker.sock:/var/run/docker.sock
  #    depends_on:
  #      - influxdb

  #  kapacitor:
  #    # Full tag list: https://hub.docker.com/r/library/kapacitor/tags/
  #    image: kapacitor:alpine
  #    container_name: kapacitor
  #    restart: unless-stopped
  #    extra_hosts: # for  Linux hosts since version 20.10
  #      - dockerhost:host-gateway
  #    volumes:
  #      # Mount for kapacitor data directory
  #      - ../../data/kapacitor/data/:/var/lib/kapacitor
  #      # Mount for kapacitor configuration
  #      - ./kapacitor/config/:/etc/kapacitor/
  #    # Kapacitor requires network access to Influxdb
  #    links:
  #      - influxdb
  #    ports:
  #      # The API for Kapacitor is served on port 9092
  #      - "9092:9092"

  chronograf:
    image: chronograf:1.8.10-alpine
    container_name: chronograf
    restart: unless-stopped
    extra_hosts: # for  Linux hosts since version 20.10
      - dockerhost:host-gateway
    environment:
      RESOURCES_PATH: "/usr/share/chronograf/resources"
    volumes:
      # Mount for chronograf database
      - ../../data/chronograf/data/:/var/lib/chronograf/
      - ./chronograf/resources/config.src:/usr/share/chronograf/resources/config.src
    #      - ./chronograf/resources/sandbox-kapa.kap:/usr/share/chronograf/resources/sandbox-kapa.kap
    links:
      # Chronograf requires network access to InfluxDB and Kapacitor
      - influxdb
    #      - kapacitor
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - influxdb
    #      - kapacitor
    #      - telegraf
  #influx end
