services:
#  grafana begin
  grafana:
    extends:
      file: ../metrics/grafana/grafana/docker-compose-grafana.yml
      service: grafana
    networks:
      op-local:
        ipv4_address: 192.168.10.44
  #grafana end

  #prometheus begin
  prometheus:
    extends:
      file: ../metrics/grafana/prometheus/docker-compose-prometheus.yml
      service: prometheus
    networks:
      op-local:
        ipv4_address: 192.168.10.45
  #prometheus end

  #influx grafana begin
  influxdb:
    extends:
      file: ../metrics/grafana/influx/docker-compose-influx.yml
      service: influxdb
    networks:
      op-local:
        ipv4_address: 192.168.10.15

  telegraf:
    extends:
      file: ../metrics/grafana/influx/docker-compose-influx.yml
      service: telegraf
    networks:
      op-local:
        ipv4_address: 192.168.10.16
    depends_on:
      influxdb:
        condition: service_started

  kapacitor:
    extends:
      file: ../metrics/grafana/influx/docker-compose-influx.yml
      service: kapacitor
    networks:
      op-local:
        ipv4_address: 192.168.10.17
    depends_on:
      influxdb:
        condition: service_started

  chronograf:
    extends:
      file: ../metrics/grafana/influx/docker-compose-influx.yml
      service: chronograf
    networks:
      op-local:
        ipv4_address: 192.168.10.18

    depends_on:
      influxdb:
        condition: service_started
      kapacitor:
        condition: service_started
      telegraf:
        condition: service_started
  #influx grafana end

networks:
  op-local:
    name: op-local
    external: true
volumes:
  grafana-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../metrics/data/grafana/data'
